// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import "@vue/runtime-core";

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    ColorPicker: typeof import("./src/components/color-picker.vue")["default"];
    QrScanner: typeof import("./src/components/qr-scanner.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    VApp: typeof import("vuetify/lib")["VApp"];
    VColorPicker: typeof import("vuetify/lib")["VColorPicker"];
    VMain: typeof import("vuetify/lib")["VMain"];
    VProgressCircular: typeof import("vuetify/lib")["VProgressCircular"];
    VSnackbar: typeof import("vuetify/lib")["VSnackbar"];
  }
}

export {};
