// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
export {};

declare module "vue" {
  export interface GlobalComponents {
    ColorPicker: typeof import("./components/color-picker.vue")["default"];
    DatePicker: typeof import("./components/date-picker.vue")["default"];
    QrScanner: typeof import("./components/qr-scanner.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    TimePicker: typeof import("./components/time-picker.vue")["default"];
    VApp: typeof import("vuetify/lib")["VApp"];
    VColorPicker: typeof import("vuetify/lib")["VColorPicker"];
    VDatePicker: typeof import("vuetify/lib")["VDatePicker"];
    VMain: typeof import("vuetify/lib")["VMain"];
    VProgressCircular: typeof import("vuetify/lib")["VProgressCircular"];
    VSnackbar: typeof import("vuetify/lib")["VSnackbar"];
    VTimePicker: typeof import("vuetify/lib")["VTimePicker"];
  }
}
