// Generated by `deno task generate:validators`
import { z } from "../deps/zod.ts";

export const colorPickerConfigSchema = z.object({
  baseUrl: z.string().url().optional().default(
    "https://grammy-components.pages.dev",
  ),
  path: z.string().optional().default("color-picker"),
});

export const colorPickerPropsSchema = z.object({
  language: z.string().optional(),
  callbackUrl: z.string().url().optional(),
  sendButton: z.object({
    hintText: z.string(),
    submitText: z.string(),
  }).optional(),
});

export const colorPickerResultSchema = z.object({
  type: z.literal("color-picker"),
  hex: z.string().regex(/^#([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$/),
});
