// Generated by `deno task generate:validators`
import { z } from "../deps/zod.ts";

export const datePickerConfigSchema = z.object({
  baseUrl: z.string().url().optional().default(
    "https://grammy-components.pages.dev",
  ),
  path: z.string().optional().default("date-picker"),
});

export const datePickerPropsSchema = z.object({
  language: z.string().optional(),
  callbackUrl: z.string().url().optional(),
  sendButton: z.object({
    hintText: z.string(),
    submitText: z.string(),
  }).optional(),
});

export const datePickerResultSchema = z.object({
  type: z.literal("date-picker"),
  date: z.date(),
});
